# Use an official Python runtime as a parent image
FROM python:3.12-slim # Updated base image

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 # Use key=value format
ENV PYTHONUNBUFFERED=1 # Use key=value format

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy project
COPY . /app/

# Expose port 8000
EXPOSE 8000

# Run entrypoint.sh when the container launches
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
# We will use docker-compose command instead for flexibility
